// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// When set in a
/// [SlurmNodeSet][google.cloud.hypercomputecluster.v1.SlurmNodeSet], indicates
/// that the nodeset should be backed by Compute Engine VM instances.
///
/// [google.cloud.hypercomputecluster.v1.SlurmNodeSet]: <doc:SlurmNodeSet>
public struct ComputeInstanceSlurmNodeSet: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. [Startup
  /// script](https://cloud.google.com/compute/docs/instances/startup-scripts/linux)
  /// to be run on each VM instance in the nodeset. Max 256KB.
  public var startupScript: Swift.String = Swift.String()

  /// Optional.
  /// [Labels](https://cloud.google.com/compute/docs/labeling-resources) that
  /// should be applied to each VM instance in the nodeset.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Boot disk for the compute instance
  public var bootDisk: BootDisk? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ComputeInstanceSlurmNodeSet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeInstanceSlurmNodeSet().with { $0.startupScript = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let startupScript = CodingKeys(stringValue: "startupScript")
    static let labels = CodingKeys(stringValue: "labels")
    static let bootDisk = CodingKeys(stringValue: "bootDisk")

    static let _knownKeys: Set<Swift.String> = [
      "startupScript",
      "labels",
      "bootDisk",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .startupScript) {
      self.startupScript = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.bootDisk = try container.decodeIfPresent(BootDisk.self, forKey: .bootDisk)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.startupScript, forKey: .startupScript)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.bootDisk, forKey: .bootDisk)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.ComputeInstanceSlurmNodeSet"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
