// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Describes how a compute resource should be created at runtime.
public struct ComputeResourceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Particular type of configuration for this compute resource.
  public var config: OneOf_Config? = nil

  /// Initialize a new instance of `ComputeResourceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeResourceConfig().with { $0.newOnDemandInstances = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case newOnDemandInstances = "newOnDemandInstances"
    case newSpotInstances = "newSpotInstances"
    case newReservedInstances = "newReservedInstances"
    case newFlexStartInstances = "newFlexStartInstances"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var config: OneOf_Config? = nil
    let configCheckAndSet = {
      if config != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'config'"))
      }
      config = $0
    }
    if let newOnDemandInstances = try container.decodeIfPresent(
      NewOnDemandInstancesConfig?.self, forKey: .newOnDemandInstances)
    {
      try configCheckAndSet(.newOnDemandInstances(newOnDemandInstances))
    }
    if let newSpotInstances = try container.decodeIfPresent(
      NewSpotInstancesConfig?.self, forKey: .newSpotInstances)
    {
      try configCheckAndSet(.newSpotInstances(newSpotInstances))
    }
    if let newReservedInstances = try container.decodeIfPresent(
      NewReservedInstancesConfig?.self, forKey: .newReservedInstances)
    {
      try configCheckAndSet(.newReservedInstances(newReservedInstances))
    }
    if let newFlexStartInstances = try container.decodeIfPresent(
      NewFlexStartInstancesConfig?.self, forKey: .newFlexStartInstances)
    {
      try configCheckAndSet(.newFlexStartInstances(newFlexStartInstances))
    }
    self.config = config
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.config {
      switch choice {
      case .newOnDemandInstances(let value):
        try container.encode(value, forKey: .newOnDemandInstances)
      case .newSpotInstances(let value):
        try container.encode(value, forKey: .newSpotInstances)
      case .newReservedInstances(let value):
        try container.encode(value, forKey: .newReservedInstances)
      case .newFlexStartInstances(let value):
        try container.encode(value, forKey: .newFlexStartInstances)
      }
    }
  }

  /// Particular type of configuration for this compute resource.
  public enum OneOf_Config: Codable, Equatable, Sendable {
    /// Optional. Immutable. If set, indicates that this resource should use
    /// on-demand VMs.
    indirect case newOnDemandInstances(NewOnDemandInstancesConfig?)
    /// Optional. Immutable. If set, indicates that this resource should use spot
    /// VMs.
    indirect case newSpotInstances(NewSpotInstancesConfig?)
    /// Optional. Immutable. If set, indicates that this resource should use
    /// reserved VMs.
    indirect case newReservedInstances(NewReservedInstancesConfig?)
    /// Optional. Immutable. If set, indicates that this resource should use
    /// flex-start VMs.
    indirect case newFlexStartInstances(NewFlexStartInstancesConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.ComputeResourceConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
