// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ListClusters][google.cloud.hypercomputecluster.v1.HypercomputeCluster.ListClusters].
///
/// [google.cloud.hypercomputecluster.v1.HypercomputeCluster.ListClusters]: <doc:HypercomputeClusterClient/listClusters(request:)>
public struct ListClustersRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Parent location of the clusters to list, in the format
  /// `projects/{project}/locations/{location}`.
  public var parent: Swift.String = Swift.String()

  /// Optional. Maximum number of clusters to return. The service may return
  /// fewer than this value.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token received from a previous `ListClusters` call.
  /// Provide this to retrieve the subsequent page. When paginating, all other
  /// parameters provided to `ListClusters` must match the call that provided the
  /// page token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. [Filter](https://google.aip.dev/160) to apply to the returned
  /// results.
  public var filter: Swift.String = Swift.String()

  /// Optional. How to order the resulting clusters. Must be one of the following
  /// strings:
  ///
  /// * `name`
  /// * `name desc`
  /// * `create_time`
  /// * `create_time desc`
  ///
  /// If not specified, clusters will be returned in an arbitrary order.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListClustersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListClustersRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.ListClustersRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
