// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes how a network resource should be initialized. Each network resource
/// can either be imported from an existing Google Cloud resource or initialized
/// when the cluster is created.
public struct NetworkResourceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Particular type of configuration for this network resource.
  public var config: OneOf_Config? = nil

  /// Initialize a new instance of `NetworkResourceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkResourceConfig().with { $0.newNetwork = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case newNetwork = "newNetwork"
    case existingNetwork = "existingNetwork"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var config: OneOf_Config? = nil
    let configCheckAndSet = {
      if config != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'config'"))
      }
      config = $0
    }
    if let newNetwork = try container.decodeIfPresent(NewNetworkConfig?.self, forKey: .newNetwork) {
      try configCheckAndSet(.newNetwork(newNetwork))
    }
    if let existingNetwork = try container.decodeIfPresent(
      ExistingNetworkConfig?.self, forKey: .existingNetwork)
    {
      try configCheckAndSet(.existingNetwork(existingNetwork))
    }
    self.config = config
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.config {
      switch choice {
      case .newNetwork(let value):
        try container.encode(value, forKey: .newNetwork)
      case .existingNetwork(let value):
        try container.encode(value, forKey: .existingNetwork)
      }
    }
  }

  /// Particular type of configuration for this network resource.
  public enum OneOf_Config: Codable, Equatable, Sendable {
    /// Optional. Immutable. If set, indicates that a new network should be
    /// created.
    indirect case newNetwork(NewNetworkConfig?)
    /// Optional. Immutable. If set, indicates that an existing network should be
    /// imported.
    indirect case existingNetwork(ExistingNetworkConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.NetworkResourceConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
