// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// When set in a
/// [StorageResourceConfig][google.cloud.hypercomputecluster.v1.StorageResourceConfig],
/// indicates that a new [Google Cloud Storage](https://cloud.google.com/storage)
/// bucket should be created.
///
/// [google.cloud.hypercomputecluster.v1.StorageResourceConfig]: <doc:StorageResourceConfig>
public struct NewBucketConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Immutable. Name of the Cloud Storage bucket to create.
  public var bucket: Swift.String = Swift.String()

  /// Optional. Immutable. If set, indicates that the bucket should use
  /// [hierarchical
  /// namespaces](https://cloud.google.com/storage/docs/hns-overview).
  public var hierarchicalNamespace: GcsHierarchicalNamespaceConfig? = nil

  /// Storage class of the bucket, which can be set automatically or explicitly.
  public var option: OneOf_Option? = nil

  /// Initialize a new instance of `NewBucketConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NewBucketConfig().with { $0.autoclass = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case autoclass = "autoclass"
    case storageClass = "storageClass"
    case bucket = "bucket"
    case hierarchicalNamespace = "hierarchicalNamespace"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.bucket = try container.decode(Swift.String.self, forKey: .bucket)
    self.hierarchicalNamespace = try container.decodeIfPresent(
      GcsHierarchicalNamespaceConfig.self, forKey: .hierarchicalNamespace)

    var option: OneOf_Option? = nil
    let optionCheckAndSet = {
      if option != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'option'"))
      }
      option = $0
    }
    if let autoclass = try container.decodeIfPresent(GcsAutoclassConfig?.self, forKey: .autoclass) {
      try optionCheckAndSet(.autoclass(autoclass))
    }
    if let storageClass = try container.decodeIfPresent(
      NewBucketConfig.StorageClass.self, forKey: .storageClass)
    {
      try optionCheckAndSet(.storageClass(storageClass))
    }
    self.option = option
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.bucket, forKey: .bucket)
    try container.encode(self.hierarchicalNamespace, forKey: .hierarchicalNamespace)

    if let choice = self.option {
      switch choice {
      case .autoclass(let value):
        try container.encode(value, forKey: .autoclass)
      case .storageClass(let value):
        try container.encode(value, forKey: .storageClass)
      }
    }
  }

  /// [Storage class](https://cloud.google.com/storage/docs/storage-classes) for
  /// a Cloud Storage bucket.
  public enum StorageClass: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Best for data that is frequently accessed.
    case standard
    /// Low-cost storage for data that is accessed less frequently.
    case nearline
    /// Very low-cost storage for infrequently accessed data.
    case coldline
    /// Lowest-cost storage for data archiving, online backup, and disaster
    /// recovery.
    case archive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standard: return 1
      case .nearline: return 2
      case .coldline: return 3
      case .archive: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STORAGE_CLASS_UNSPECIFIED"
      case .standard: return "STANDARD"
      case .nearline: return "NEARLINE"
      case .coldline: return "COLDLINE"
      case .archive: return "ARCHIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:StorageClass/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STORAGE_CLASS_UNSPECIFIED": self = .unspecified
      case "STANDARD": self = .standard
      case "NEARLINE": self = .nearline
      case "COLDLINE": self = .coldline
      case "ARCHIVE": self = .archive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:StorageClass/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standard
      case 2: self = .nearline
      case 3: self = .coldline
      case 4: self = .archive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .standard: return try container.encode(1)
      case .nearline: return try container.encode(2)
      case .coldline: return try container.encode(3)
      case .archive: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Storage class of the bucket, which can be set automatically or explicitly.
  public enum OneOf_Option: Codable, Equatable, Sendable {
    /// Optional. Immutable. If set, indicates that the bucket should use
    /// [Autoclass](https://cloud.google.com/storage/docs/autoclass).
    indirect case autoclass(GcsAutoclassConfig?)
    /// Optional. Immutable. If set, uses the provided storage class as the
    /// bucket's default storage class.
    case storageClass(NewBucketConfig.StorageClass)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.NewBucketConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
