// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// When set in a
/// [StorageResourceConfig][google.cloud.hypercomputecluster.v1.StorageResourceConfig],
/// indicates that a new [Filestore](https://cloud.google.com/filestore) instance
/// should be created.
///
/// [google.cloud.hypercomputecluster.v1.StorageResourceConfig]: <doc:StorageResourceConfig>
public struct NewFilestoreConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Immutable. Name of the Filestore instance to create, in the
  /// format `projects/{project}/locations/{location}/instances/{instance}`
  public var filestore: Swift.String = Swift.String()

  /// Optional. Immutable. Description of the instance. Maximum of 2048
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Required. Immutable. File system shares on the instance. Exactly one file
  /// share must be specified.
  public var fileShares: [FileShareConfig] = []

  /// Required. Immutable. Service tier to use for the instance.
  public var tier: NewFilestoreConfig.Tier = NewFilestoreConfig.Tier()

  /// Optional. Immutable. Access protocol to use for all file shares in the
  /// instance. Defaults to NFS V3 if not set.
  public var `protocol`: NewFilestoreConfig.Protocol_ = NewFilestoreConfig.Protocol_()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NewFilestoreConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NewFilestoreConfig().with { $0.filestore = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let filestore = CodingKeys(stringValue: "filestore")
    static let description = CodingKeys(stringValue: "description")
    static let fileShares = CodingKeys(stringValue: "fileShares")
    static let tier = CodingKeys(stringValue: "tier")
    static let `protocol` = CodingKeys(stringValue: "protocol")

    static let _knownKeys: Set<Swift.String> = [
      "filestore",
      "description",
      "fileShares",
      "tier",
      "protocol",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filestore) {
      self.filestore = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([FileShareConfig].self, forKey: .fileShares) {
      self.fileShares = value
    }
    if let value = try container.decodeIfPresent(NewFilestoreConfig.Tier.self, forKey: .tier) {
      self.tier = value
    }
    if let value = try container.decodeIfPresent(
      NewFilestoreConfig.Protocol_.self, forKey: .`protocol`)
    {
      self.`protocol` = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.filestore, forKey: .filestore)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.fileShares, forKey: .fileShares)
    try container.encode(self.tier, forKey: .tier)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Available [service
  /// tiers](https://cloud.google.com/filestore/docs/service-tiers) for Filestore
  /// instances.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Tier: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Offers expanded capacity and performance scaling capabilities suitable
    /// for high-performance computing application requirements.
    case zonal
    /// Offers features and availability needed for mission-critical,
    /// high-performance computing workloads.
    case regional
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .zonal: return 4
      case .regional: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TIER_UNSPECIFIED"
      case .zonal: return "ZONAL"
      case .regional: return "REGIONAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Tier/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TIER_UNSPECIFIED": self = .unspecified
      case "ZONAL": self = .zonal
      case "REGIONAL": self = .regional
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Tier/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 4: self = .zonal
      case 6: self = .regional
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TIER_UNSPECIFIED")
      case .zonal: return try container.encode("ZONAL")
      case .regional: return try container.encode("REGIONAL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// File access protocol for Filestore instances.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Protocol_: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// NFS 3.0.
    case nfsv3
    /// NFS 4.1.
    case nfsv41
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .nfsv3: return 1
      case .nfsv41: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROTOCOL_UNSPECIFIED"
      case .nfsv3: return "NFSV3"
      case .nfsv41: return "NFSV41"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Protocol_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROTOCOL_UNSPECIFIED": self = .unspecified
      case "NFSV3": self = .nfsv3
      case "NFSV41": self = .nfsv41
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Protocol_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .nfsv3
      case 2: self = .nfsv41
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PROTOCOL_UNSPECIFIED")
      case .nfsv3: return try container.encode("NFSV3")
      case .nfsv41: return try container.encode("NFSV41")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.NewFilestoreConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
