// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// When set in a
/// [ComputeResourceConfig][google.cloud.hypercomputecluster.v1.ComputeResourceConfig],
/// indicates that VM instances should be created using [Flex
/// Start](https://cloud.google.com/compute/docs/instances/provisioning-models).
///
/// [google.cloud.hypercomputecluster.v1.ComputeResourceConfig]: <doc:ComputeResourceConfig>
public struct NewFlexStartInstancesConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Immutable. Name of the zone in which VM instances should run,
  /// e.g., `us-central1-a`. Must be in the same region as the cluster, and must
  /// match the zone of any other resources specified in the cluster.
  public var zone: Swift.String = Swift.String()

  /// Required. Immutable. Name of the Compute Engine [machine
  /// type](https://cloud.google.com/compute/docs/machine-resource) to use, e.g.
  /// `n2-standard-2`.
  public var machineType: Swift.String = Swift.String()

  /// Required. Immutable. Specifies the time limit for created instances.
  /// Instances will be terminated at the end of this duration.
  public var maxDuration: GoogleCloudWkt.Duration? = nil

  /// Initialize a new instance of `NewFlexStartInstancesConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NewFlexStartInstancesConfig().with { $0.zone = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.NewFlexStartInstancesConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
