// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// When set in a
/// [StorageResourceConfig][google.cloud.hypercomputecluster.v1.StorageResourceConfig],
/// indicates that a new [Managed
/// Lustre](https://cloud.google.com/products/managed-lustre) instance should be
/// created.
///
/// [google.cloud.hypercomputecluster.v1.StorageResourceConfig]: <doc:StorageResourceConfig>
public struct NewLustreConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Immutable. Name of the Managed Lustre instance to create, in the
  /// format `projects/{project}/locations/{location}/instances/{instance}`
  public var lustre: Swift.String = Swift.String()

  /// Optional. Immutable. Description of the Managed Lustre instance. Maximum of
  /// 2048 characters.
  public var description: Swift.String = Swift.String()

  /// Required. Immutable. Filesystem name for this instance. This name is used
  /// by client-side tools, including when mounting the instance. Must be 8
  /// characters or less and can only contain letters and numbers.
  public var filesystem: Swift.String = Swift.String()

  /// Required. Immutable. Storage capacity of the instance in gibibytes (GiB).
  /// Allowed values are between 18000 and 7632000.
  public var capacityGb: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `NewLustreConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NewLustreConfig().with { $0.lustre = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.NewLustreConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
