// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// When set in a
/// [ComputeResourceConfig][google.cloud.hypercomputecluster.v1.ComputeResourceConfig],
/// indicates that [spot
/// VM](https://cloud.google.com/compute/docs/instances/spot) instances should be
/// created.
///
/// [google.cloud.hypercomputecluster.v1.ComputeResourceConfig]: <doc:ComputeResourceConfig>
public struct NewSpotInstancesConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Immutable. Name of the zone in which VM instances should run,
  /// e.g., `us-central1-a`. Must be in the same region as the cluster, and must
  /// match the zone of any other resources specified in the cluster.
  public var zone: Swift.String = Swift.String()

  /// Required. Immutable. Name of the Compute Engine [machine
  /// type](https://cloud.google.com/compute/docs/machine-resource) to use, e.g.
  /// `n2-standard-2`.
  public var machineType: Swift.String = Swift.String()

  /// Optional. Termination action for the instance. If not specified, Compute
  /// Engine sets the termination action to DELETE.
  public var terminationAction: NewSpotInstancesConfig.TerminationAction =
    NewSpotInstancesConfig.TerminationAction()

  /// Initialize a new instance of `NewSpotInstancesConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NewSpotInstancesConfig().with { $0.zone = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Specifies the termination action of the instance
  public enum TerminationAction: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Compute Engine stops the Spot VM on preemption.
    case stop
    /// Compute Engine deletes the Spot VM on preemption.
    case delete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .stop: return 1
      case .delete: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TERMINATION_ACTION_UNSPECIFIED"
      case .stop: return "STOP"
      case .delete: return "DELETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TerminationAction/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TERMINATION_ACTION_UNSPECIFIED": self = .unspecified
      case "STOP": self = .stop
      case "DELETE": self = .delete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TerminationAction/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .stop
      case 2: self = .delete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .stop: return try container.encode(1)
      case .delete: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.NewSpotInstancesConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
