// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message describing the status of a single step in a cluster mutation
/// long-running operation.
public struct OperationStep: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. State of the operation step.
  public var state: OperationStep.State = OperationStep.State()

  /// Step of the operation.
  public var type: OneOf_Type_? = nil

  /// Initialize a new instance of `OperationStep`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationStep().with { $0.createNetwork = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case createNetwork = "createNetwork"
    case createPrivateServiceAccess = "createPrivateServiceAccess"
    case createFilestoreInstance = "createFilestoreInstance"
    case createStorageBucket = "createStorageBucket"
    case createLustreInstance = "createLustreInstance"
    case createOrchestrator = "createOrchestrator"
    case createNodeset = "createNodeset"
    case createPartition = "createPartition"
    case createLoginNode = "createLoginNode"
    case checkClusterHealth = "checkClusterHealth"
    case updateOrchestrator = "updateOrchestrator"
    case updateNodeset = "updateNodeset"
    case updatePartition = "updatePartition"
    case updateLoginNode = "updateLoginNode"
    case deleteOrchestrator = "deleteOrchestrator"
    case deleteNodeset = "deleteNodeset"
    case deletePartition = "deletePartition"
    case deleteLoginNode = "deleteLoginNode"
    case deleteFilestoreInstance = "deleteFilestoreInstance"
    case deleteStorageBucket = "deleteStorageBucket"
    case deleteLustreInstance = "deleteLustreInstance"
    case deletePrivateServiceAccess = "deletePrivateServiceAccess"
    case deleteNetwork = "deleteNetwork"
    case state = "state"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.state = try container.decode(OperationStep.State.self, forKey: .state)

    var type: OneOf_Type_? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let createNetwork = try container.decodeIfPresent(
      CreateNetwork?.self, forKey: .createNetwork)
    {
      try typeCheckAndSet(.createNetwork(createNetwork))
    }
    if let createPrivateServiceAccess = try container.decodeIfPresent(
      CreatePrivateServiceAccess?.self, forKey: .createPrivateServiceAccess)
    {
      try typeCheckAndSet(.createPrivateServiceAccess(createPrivateServiceAccess))
    }
    if let createFilestoreInstance = try container.decodeIfPresent(
      CreateFilestoreInstance?.self, forKey: .createFilestoreInstance)
    {
      try typeCheckAndSet(.createFilestoreInstance(createFilestoreInstance))
    }
    if let createStorageBucket = try container.decodeIfPresent(
      CreateStorageBucket?.self, forKey: .createStorageBucket)
    {
      try typeCheckAndSet(.createStorageBucket(createStorageBucket))
    }
    if let createLustreInstance = try container.decodeIfPresent(
      CreateLustreInstance?.self, forKey: .createLustreInstance)
    {
      try typeCheckAndSet(.createLustreInstance(createLustreInstance))
    }
    if let createOrchestrator = try container.decodeIfPresent(
      CreateOrchestrator?.self, forKey: .createOrchestrator)
    {
      try typeCheckAndSet(.createOrchestrator(createOrchestrator))
    }
    if let createNodeset = try container.decodeIfPresent(
      CreateNodeset?.self, forKey: .createNodeset)
    {
      try typeCheckAndSet(.createNodeset(createNodeset))
    }
    if let createPartition = try container.decodeIfPresent(
      CreatePartition?.self, forKey: .createPartition)
    {
      try typeCheckAndSet(.createPartition(createPartition))
    }
    if let createLoginNode = try container.decodeIfPresent(
      CreateLoginNode?.self, forKey: .createLoginNode)
    {
      try typeCheckAndSet(.createLoginNode(createLoginNode))
    }
    if let checkClusterHealth = try container.decodeIfPresent(
      CheckClusterHealth?.self, forKey: .checkClusterHealth)
    {
      try typeCheckAndSet(.checkClusterHealth(checkClusterHealth))
    }
    if let updateOrchestrator = try container.decodeIfPresent(
      UpdateOrchestrator?.self, forKey: .updateOrchestrator)
    {
      try typeCheckAndSet(.updateOrchestrator(updateOrchestrator))
    }
    if let updateNodeset = try container.decodeIfPresent(
      UpdateNodeset?.self, forKey: .updateNodeset)
    {
      try typeCheckAndSet(.updateNodeset(updateNodeset))
    }
    if let updatePartition = try container.decodeIfPresent(
      UpdatePartition?.self, forKey: .updatePartition)
    {
      try typeCheckAndSet(.updatePartition(updatePartition))
    }
    if let updateLoginNode = try container.decodeIfPresent(
      UpdateLoginNode?.self, forKey: .updateLoginNode)
    {
      try typeCheckAndSet(.updateLoginNode(updateLoginNode))
    }
    if let deleteOrchestrator = try container.decodeIfPresent(
      DeleteOrchestrator?.self, forKey: .deleteOrchestrator)
    {
      try typeCheckAndSet(.deleteOrchestrator(deleteOrchestrator))
    }
    if let deleteNodeset = try container.decodeIfPresent(
      DeleteNodeset?.self, forKey: .deleteNodeset)
    {
      try typeCheckAndSet(.deleteNodeset(deleteNodeset))
    }
    if let deletePartition = try container.decodeIfPresent(
      DeletePartition?.self, forKey: .deletePartition)
    {
      try typeCheckAndSet(.deletePartition(deletePartition))
    }
    if let deleteLoginNode = try container.decodeIfPresent(
      DeleteLoginNode?.self, forKey: .deleteLoginNode)
    {
      try typeCheckAndSet(.deleteLoginNode(deleteLoginNode))
    }
    if let deleteFilestoreInstance = try container.decodeIfPresent(
      DeleteFilestoreInstance?.self, forKey: .deleteFilestoreInstance)
    {
      try typeCheckAndSet(.deleteFilestoreInstance(deleteFilestoreInstance))
    }
    if let deleteStorageBucket = try container.decodeIfPresent(
      DeleteStorageBucket?.self, forKey: .deleteStorageBucket)
    {
      try typeCheckAndSet(.deleteStorageBucket(deleteStorageBucket))
    }
    if let deleteLustreInstance = try container.decodeIfPresent(
      DeleteLustreInstance?.self, forKey: .deleteLustreInstance)
    {
      try typeCheckAndSet(.deleteLustreInstance(deleteLustreInstance))
    }
    if let deletePrivateServiceAccess = try container.decodeIfPresent(
      DeletePrivateServiceAccess?.self, forKey: .deletePrivateServiceAccess)
    {
      try typeCheckAndSet(.deletePrivateServiceAccess(deletePrivateServiceAccess))
    }
    if let deleteNetwork = try container.decodeIfPresent(
      DeleteNetwork?.self, forKey: .deleteNetwork)
    {
      try typeCheckAndSet(.deleteNetwork(deleteNetwork))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.state, forKey: .state)

    if let choice = self.type {
      switch choice {
      case .createNetwork(let value):
        try container.encode(value, forKey: .createNetwork)
      case .createPrivateServiceAccess(let value):
        try container.encode(value, forKey: .createPrivateServiceAccess)
      case .createFilestoreInstance(let value):
        try container.encode(value, forKey: .createFilestoreInstance)
      case .createStorageBucket(let value):
        try container.encode(value, forKey: .createStorageBucket)
      case .createLustreInstance(let value):
        try container.encode(value, forKey: .createLustreInstance)
      case .createOrchestrator(let value):
        try container.encode(value, forKey: .createOrchestrator)
      case .createNodeset(let value):
        try container.encode(value, forKey: .createNodeset)
      case .createPartition(let value):
        try container.encode(value, forKey: .createPartition)
      case .createLoginNode(let value):
        try container.encode(value, forKey: .createLoginNode)
      case .checkClusterHealth(let value):
        try container.encode(value, forKey: .checkClusterHealth)
      case .updateOrchestrator(let value):
        try container.encode(value, forKey: .updateOrchestrator)
      case .updateNodeset(let value):
        try container.encode(value, forKey: .updateNodeset)
      case .updatePartition(let value):
        try container.encode(value, forKey: .updatePartition)
      case .updateLoginNode(let value):
        try container.encode(value, forKey: .updateLoginNode)
      case .deleteOrchestrator(let value):
        try container.encode(value, forKey: .deleteOrchestrator)
      case .deleteNodeset(let value):
        try container.encode(value, forKey: .deleteNodeset)
      case .deletePartition(let value):
        try container.encode(value, forKey: .deletePartition)
      case .deleteLoginNode(let value):
        try container.encode(value, forKey: .deleteLoginNode)
      case .deleteFilestoreInstance(let value):
        try container.encode(value, forKey: .deleteFilestoreInstance)
      case .deleteStorageBucket(let value):
        try container.encode(value, forKey: .deleteStorageBucket)
      case .deleteLustreInstance(let value):
        try container.encode(value, forKey: .deleteLustreInstance)
      case .deletePrivateServiceAccess(let value):
        try container.encode(value, forKey: .deletePrivateServiceAccess)
      case .deleteNetwork(let value):
        try container.encode(value, forKey: .deleteNetwork)
      }
    }
  }

  /// State of the operation step.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Initial state before step execution starts.
    case waiting
    /// Step execution is running in progress.
    case inProgress
    /// Step execution is completed.
    case done
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .waiting: return 1
      case .inProgress: return 2
      case .done: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .waiting: return "WAITING"
      case .inProgress: return "IN_PROGRESS"
      case .done: return "DONE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "WAITING": self = .waiting
      case "IN_PROGRESS": self = .inProgress
      case "DONE": self = .done
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .waiting
      case 2: self = .inProgress
      case 3: self = .done
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .waiting: return try container.encode(1)
      case .inProgress: return try container.encode(2)
      case .done: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Step of the operation.
  public enum OneOf_Type_: Codable, Equatable, Sendable {
    /// Output only. If set, indicates that new network creation is part of the
    /// operation.
    indirect case createNetwork(CreateNetwork?)
    /// Output only. If set, indicates that new private service access creation
    /// is part of the operation.
    indirect case createPrivateServiceAccess(CreatePrivateServiceAccess?)
    /// Output only. If set, indicates that new Filestore instance creation is
    /// part of the operation.
    indirect case createFilestoreInstance(CreateFilestoreInstance?)
    /// Output only. If set, indicates that new Cloud Storage bucket creation is
    /// part of the operation.
    indirect case createStorageBucket(CreateStorageBucket?)
    /// Output only. If set, indicates that new Lustre instance creation is part
    /// of the operation.
    indirect case createLustreInstance(CreateLustreInstance?)
    /// Output only. If set, indicates that orchestrator creation is part of the
    /// operation.
    indirect case createOrchestrator(CreateOrchestrator?)
    /// Output only. If set, indicates that new nodeset creation is part of the
    /// operation.
    indirect case createNodeset(CreateNodeset?)
    /// Output only. If set, indicates that new partition creation is part of the
    /// operation.
    indirect case createPartition(CreatePartition?)
    /// Output only. If set, indicates that new login node creation is part of
    /// the operation.
    indirect case createLoginNode(CreateLoginNode?)
    /// Output only. If set, indicates that cluster health check is part of the
    /// operation.
    indirect case checkClusterHealth(CheckClusterHealth?)
    /// Output only. If set, indicates that an orchestrator update is part of the
    /// operation.
    indirect case updateOrchestrator(UpdateOrchestrator?)
    /// Output only. If set, indicates that nodeset update is part of the
    /// operation.
    indirect case updateNodeset(UpdateNodeset?)
    /// Output only. If set, indicates that partition update is part of the
    /// operation.
    indirect case updatePartition(UpdatePartition?)
    /// Output only. If set, indicates that login node update is part of the
    /// operation.
    indirect case updateLoginNode(UpdateLoginNode?)
    /// Output only. If set, indicates that orchestrator deletion is part of the
    /// operation.
    indirect case deleteOrchestrator(DeleteOrchestrator?)
    /// Output only. If set, indicates that nodeset deletion is part of the
    /// operation.
    indirect case deleteNodeset(DeleteNodeset?)
    /// Output only. If set, indicates that partition deletion is part of the
    /// operation.
    indirect case deletePartition(DeletePartition?)
    /// Output only. If set, indicates that login node deletion is part of the
    /// operation.
    indirect case deleteLoginNode(DeleteLoginNode?)
    /// Output only. If set, indicates that Filestore instance deletion is part
    /// of the operation.
    indirect case deleteFilestoreInstance(DeleteFilestoreInstance?)
    /// Output only. If set, indicates that Cloud Storage bucket deletion is part
    /// of the operation.
    indirect case deleteStorageBucket(DeleteStorageBucket?)
    /// Output only. If set, indicates that Lustre instance deletion is part of
    /// the operation.
    indirect case deleteLustreInstance(DeleteLustreInstance?)
    /// Output only. If set, indicates that private service access deletion is
    /// part of the operation.
    indirect case deletePrivateServiceAccess(DeletePrivateServiceAccess?)
    /// Output only. If set, indicates that network deletion is part of the
    /// operation.
    indirect case deleteNetwork(DeleteNetwork?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.OperationStep"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
