// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The component responsible for scheduling and running workloads on the
/// cluster as well as providing the user interface for interacting with the
/// cluster at runtime.
public struct Orchestrator: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Particular type of orchestrator to use in this cluster.
  public var option: OneOf_Option? = nil

  /// Initialize a new instance of `Orchestrator`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Orchestrator().with { $0.slurm = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case slurm = "slurm"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var option: OneOf_Option? = nil
    let optionCheckAndSet = {
      if option != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'option'"))
      }
      option = $0
    }
    if let slurm = try container.decodeIfPresent(SlurmOrchestrator?.self, forKey: .slurm) {
      try optionCheckAndSet(.slurm(slurm))
    }
    self.option = option
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.option {
      switch choice {
      case .slurm(let value):
        try container.encode(value, forKey: .slurm)
      }
    }
  }

  /// Particular type of orchestrator to use in this cluster.
  public enum OneOf_Option: Codable, Equatable, Sendable {
    /// Optional. If set, indicates that the cluster should use Slurm as the
    /// orchestrator.
    indirect case slurm(SlurmOrchestrator?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.Orchestrator"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
