// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// When set in [Orchestrator][google.cloud.hypercomputecluster.v1.Orchestrator],
/// indicates that the cluster should use [Slurm](https://slurm.schedmd.com/) as
/// the orchestrator.
///
/// [google.cloud.hypercomputecluster.v1.Orchestrator]: <doc:Orchestrator>
public struct SlurmOrchestrator: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Configuration for login nodes, which allow users to access the
  /// cluster over SSH.
  public var loginNodes: SlurmLoginNodes? = nil

  /// Optional. Compute resource configuration for the Slurm nodesets in your
  /// cluster. If not specified, the cluster won't create any nodes.
  public var nodeSets: [SlurmNodeSet] = []

  /// Optional. Configuration for the Slurm partitions in your cluster. Each
  /// partition can contain one or more nodesets, and you can submit separate
  /// jobs on each partition. If you don't specify at least one partition in your
  /// cluster, you can't submit jobs to the cluster.
  public var partitions: [SlurmPartition] = []

  /// Optional. Default partition to use for submitted jobs that do not
  /// explicitly specify a partition. Required if and only if there is more than
  /// one partition, in which case it must match the id of one of the partitions.
  public var defaultPartition: Swift.String = Swift.String()

  /// Optional. Slurm [prolog
  /// scripts](https://slurm.schedmd.com/prolog_epilog.html), which will be
  /// executed by compute nodes before a node begins running a new job. Values
  /// must not be empty.
  public var prologBashScripts: [Swift.String] = []

  /// Optional. Slurm [epilog
  /// scripts](https://slurm.schedmd.com/prolog_epilog.html), which will be
  /// executed by compute nodes whenever a node finishes running a job. Values
  /// must not be empty.
  public var epilogBashScripts: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SlurmOrchestrator`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SlurmOrchestrator().with { $0.loginNodes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let loginNodes = CodingKeys(stringValue: "loginNodes")
    static let nodeSets = CodingKeys(stringValue: "nodeSets")
    static let partitions = CodingKeys(stringValue: "partitions")
    static let defaultPartition = CodingKeys(stringValue: "defaultPartition")
    static let prologBashScripts = CodingKeys(stringValue: "prologBashScripts")
    static let epilogBashScripts = CodingKeys(stringValue: "epilogBashScripts")

    static let _knownKeys: Set<Swift.String> = [
      "loginNodes",
      "nodeSets",
      "partitions",
      "defaultPartition",
      "prologBashScripts",
      "epilogBashScripts",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.loginNodes = try container.decodeIfPresent(SlurmLoginNodes.self, forKey: .loginNodes)
    if let value = try container.decodeIfPresent([SlurmNodeSet].self, forKey: .nodeSets) {
      self.nodeSets = value
    }
    if let value = try container.decodeIfPresent([SlurmPartition].self, forKey: .partitions) {
      self.partitions = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .defaultPartition) {
      self.defaultPartition = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .prologBashScripts) {
      self.prologBashScripts = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .epilogBashScripts) {
      self.epilogBashScripts = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.loginNodes, forKey: .loginNodes)
    try container.encode(self.nodeSets, forKey: .nodeSets)
    try container.encode(self.partitions, forKey: .partitions)
    try container.encode(self.defaultPartition, forKey: .defaultPartition)
    try container.encode(self.prologBashScripts, forKey: .prologBashScripts)
    try container.encode(self.epilogBashScripts, forKey: .epilogBashScripts)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.SlurmOrchestrator"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
