// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Configuration for Slurm nodesets in the cluster. Nodesets are groups of
/// compute nodes used by Slurm that are responsible for running workloads
/// submitted to the cluster.
public struct SlurmNodeSet: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Identifier for the nodeset, which allows it to be referenced by
  /// partitions. Must conform to
  /// [RFC-1034](https://datatracker.ietf.org/doc/html/rfc1034) (lower-case,
  /// alphanumeric, and at most 63 characters).
  public var id: Swift.String = Swift.String()

  /// Optional. ID of the compute resource on which this nodeset will run. Must
  /// match a key in the cluster's
  /// [compute_resources][google.cloud.hypercomputecluster.v1.Cluster.compute_resources].
  ///
  /// [google.cloud.hypercomputecluster.v1.Cluster.compute_resources]: <doc:Cluster/computeResources>
  public var computeId: Swift.String = Swift.String()

  /// Optional. How [storage
  /// resources][google.cloud.hypercomputecluster.v1.StorageResource] should be
  /// mounted on each compute node.
  ///
  /// [google.cloud.hypercomputecluster.v1.StorageResource]: <doc:StorageResource>
  public var storageConfigs: [StorageConfig] = []

  /// Optional. Number of nodes to be statically created for this nodeset. The
  /// cluster will attempt to ensure that at least this many nodes exist at all
  /// times.
  public var staticNodeCount: Swift.Int64 = Swift.Int64()

  /// Optional. Controls how many additional nodes a cluster can bring online to
  /// handle workloads. Set this value to enable dynamic node creation and limit
  /// the number of additional nodes the cluster can bring online. Leave empty if
  /// you do not want the cluster to create nodes dynamically, and instead rely
  /// only on static nodes.
  public var maxDynamicNodeCount: Swift.Int64 = Swift.Int64()

  /// Additional configuration for the nodeset. If not set, the nodeset will
  /// use
  /// [ComputeInstanceSlurmNodeSet][google.cloud.hypercomputecluster.v1.ComputeInstanceSlurmNodeSet]
  /// with default values.
  ///
  /// [google.cloud.hypercomputecluster.v1.ComputeInstanceSlurmNodeSet]: <doc:ComputeInstanceSlurmNodeSet>
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `SlurmNodeSet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SlurmNodeSet().with { $0.computeInstance = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case computeInstance = "computeInstance"
    case id = "id"
    case computeId = "computeId"
    case storageConfigs = "storageConfigs"
    case staticNodeCount = "staticNodeCount"
    case maxDynamicNodeCount = "maxDynamicNodeCount"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.computeId = try container.decode(Swift.String.self, forKey: .computeId)
    self.storageConfigs = try container.decode([StorageConfig].self, forKey: .storageConfigs)
    self.staticNodeCount = try container.decode(Swift.Int64.self, forKey: .staticNodeCount)
    self.maxDynamicNodeCount = try container.decode(Swift.Int64.self, forKey: .maxDynamicNodeCount)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let computeInstance = try container.decodeIfPresent(
      ComputeInstanceSlurmNodeSet?.self, forKey: .computeInstance)
    {
      try typeCheckAndSet(.computeInstance(computeInstance))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.computeId, forKey: .computeId)
    try container.encode(self.storageConfigs, forKey: .storageConfigs)
    try container.encode(self.staticNodeCount, forKey: .staticNodeCount)
    try container.encode(self.maxDynamicNodeCount, forKey: .maxDynamicNodeCount)

    if let choice = self.type {
      switch choice {
      case .computeInstance(let value):
        try container.encode(value, forKey: .computeInstance)
      }
    }
  }

  /// Additional configuration for the nodeset. If not set, the nodeset will
  /// use
  /// [ComputeInstanceSlurmNodeSet][google.cloud.hypercomputecluster.v1.ComputeInstanceSlurmNodeSet]
  /// with default values.
  ///
  /// [google.cloud.hypercomputecluster.v1.ComputeInstanceSlurmNodeSet]: <doc:ComputeInstanceSlurmNodeSet>
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// Optional. If set, indicates that the nodeset should be backed by Compute
    /// Engine instances.
    indirect case computeInstance(ComputeInstanceSlurmNodeSet?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.SlurmNodeSet"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
