// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for Slurm [login
/// nodes](https://slurm.schedmd.com/quickstart_admin.html#login) in the cluster.
/// Login nodes are Compute Engine VM instances that allow users to access the
/// cluster over SSH.
public struct SlurmLoginNodes: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Number of login node instances to create.
  public var count: Swift.Int64 = Swift.Int64()

  /// Required. Name of the zone in which login nodes should run, e.g.,
  /// `us-central1-a`. Must be in the same region as the cluster, and must match
  /// the zone of any other resources specified in the cluster.
  public var zone: Swift.String = Swift.String()

  /// Required. Name of the Compute Engine [machine
  /// type](https://cloud.google.com/compute/docs/machine-resource) to use for
  /// login nodes, e.g. `n2-standard-2`.
  public var machineType: Swift.String = Swift.String()

  /// Optional. [Startup
  /// script](https://cloud.google.com/compute/docs/instances/startup-scripts/linux)
  /// to be run on each login node instance. Max 256KB.
  /// The script must complete within the system-defined default timeout of 5
  /// minutes. For tasks that require more time, consider running them in the
  /// background using methods such as `&` or `nohup`.
  public var startupScript: Swift.String = Swift.String()

  /// Optional. Whether [OS Login](https://cloud.google.com/compute/docs/oslogin)
  /// should be enabled on login node instances.
  public var enableOsLogin: Swift.Bool = Swift.Bool()

  /// Optional. Whether login node instances should be assigned [external IP
  /// addresses](https://cloud.google.com/compute/docs/ip-addresses#externaladdresses).
  public var enablePublicIps: Swift.Bool = Swift.Bool()

  /// Optional.
  /// [Labels](https://cloud.google.com/compute/docs/labeling-resources) that
  /// should be applied to each login node instance.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. How [storage
  /// resources][google.cloud.hypercomputecluster.v1.StorageResource] should be
  /// mounted on each login node.
  ///
  /// [google.cloud.hypercomputecluster.v1.StorageResource]: <doc:StorageResource>
  public var storageConfigs: [StorageConfig] = []

  /// Output only. Information about the login node instances that were created
  /// in Compute Engine.
  public var instances: [ComputeInstance] = []

  /// Optional. Boot disk for the login node.
  public var bootDisk: BootDisk? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SlurmLoginNodes`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SlurmLoginNodes().with { $0.count = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let count = CodingKeys(stringValue: "count")
    static let zone = CodingKeys(stringValue: "zone")
    static let machineType = CodingKeys(stringValue: "machineType")
    static let startupScript = CodingKeys(stringValue: "startupScript")
    static let enableOsLogin = CodingKeys(stringValue: "enableOsLogin")
    static let enablePublicIps = CodingKeys(stringValue: "enablePublicIps")
    static let labels = CodingKeys(stringValue: "labels")
    static let storageConfigs = CodingKeys(stringValue: "storageConfigs")
    static let instances = CodingKeys(stringValue: "instances")
    static let bootDisk = CodingKeys(stringValue: "bootDisk")

    static let _knownKeys: Set<Swift.String> = [
      "count",
      "zone",
      "machineType",
      "startupScript",
      "enableOsLogin",
      "enablePublicIps",
      "labels",
      "storageConfigs",
      "instances",
      "bootDisk",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .count) {
      self.count = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .zone) {
      self.zone = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineType) {
      self.machineType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .startupScript) {
      self.startupScript = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableOsLogin) {
      self.enableOsLogin = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enablePublicIps) {
      self.enablePublicIps = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent([StorageConfig].self, forKey: .storageConfigs) {
      self.storageConfigs = value
    }
    if let value = try container.decodeIfPresent([ComputeInstance].self, forKey: .instances) {
      self.instances = value
    }
    self.bootDisk = try container.decodeIfPresent(BootDisk.self, forKey: .bootDisk)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.count, forKey: .count)
    try container.encode(self.zone, forKey: .zone)
    try container.encode(self.machineType, forKey: .machineType)
    try container.encode(self.startupScript, forKey: .startupScript)
    try container.encode(self.enableOsLogin, forKey: .enableOsLogin)
    try container.encode(self.enablePublicIps, forKey: .enablePublicIps)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.storageConfigs, forKey: .storageConfigs)
    try container.encode(self.instances, forKey: .instances)
    try container.encodeIfPresent(self.bootDisk, forKey: .bootDisk)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.SlurmLoginNodes"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
