// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A resource representing a form of persistent storage that is accessible to
/// compute resources in the cluster.
public struct StorageResource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Immutable. Configuration for this storage resource, which
  /// describes how it should be created or imported. This field only controls
  /// how the storage resource is initially created or imported. Subsequent
  /// changes to the storage resource should be made via the resource's API and
  /// will not be reflected in the configuration.
  public var config: StorageResourceConfig? = nil

  /// Reference to the storage resource in Google Cloud. Exactly one of these
  /// fields will be populated based on the configured type of storage resource.
  public var reference: OneOf_Reference? = nil

  /// Initialize a new instance of `StorageResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StorageResource().with { $0.filestore = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case filestore = "filestore"
    case bucket = "bucket"
    case lustre = "lustre"
    case config = "config"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.config = try container.decodeIfPresent(StorageResourceConfig.self, forKey: .config)

    var reference: OneOf_Reference? = nil
    let referenceCheckAndSet = {
      if reference != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'reference'"))
      }
      reference = $0
    }
    if let filestore = try container.decodeIfPresent(FilestoreReference?.self, forKey: .filestore) {
      try referenceCheckAndSet(.filestore(filestore))
    }
    if let bucket = try container.decodeIfPresent(BucketReference?.self, forKey: .bucket) {
      try referenceCheckAndSet(.bucket(bucket))
    }
    if let lustre = try container.decodeIfPresent(LustreReference?.self, forKey: .lustre) {
      try referenceCheckAndSet(.lustre(lustre))
    }
    self.reference = reference
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.config, forKey: .config)

    if let choice = self.reference {
      switch choice {
      case .filestore(let value):
        try container.encode(value, forKey: .filestore)
      case .bucket(let value):
        try container.encode(value, forKey: .bucket)
      case .lustre(let value):
        try container.encode(value, forKey: .lustre)
      }
    }
  }

  /// Reference to the storage resource in Google Cloud. Exactly one of these
  /// fields will be populated based on the configured type of storage resource.
  public enum OneOf_Reference: Codable, Equatable, Sendable {
    /// Reference to a Filestore instance. Populated if and only if the storage
    /// resource was configured to use Filestore.
    indirect case filestore(FilestoreReference?)
    /// Reference to a Google Cloud Storage bucket. Populated if and only if the
    /// storage resource was configured to use Google Cloud Storage.
    indirect case bucket(BucketReference?)
    /// Reference to a Managed Lustre instance. Populated if and only if the
    /// storage resource was configured to use Managed Lustre.
    indirect case lustre(LustreReference?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.StorageResource"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
