// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Description of how a [storage
/// resource][google.cloud.hypercomputecluster.v1.StorageResource] should be
/// mounted on a VM instance.
///
/// [google.cloud.hypercomputecluster.v1.StorageResource]: <doc:StorageResource>
public struct StorageConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. ID of the storage resource to mount, which must match a key in
  /// the cluster's
  /// [storage_resources][google.cloud.hypercomputecluster.v1.Cluster.storage_resources].
  ///
  /// [google.cloud.hypercomputecluster.v1.Cluster.storage_resources]: <doc:Cluster/storageResources>
  public var id: Swift.String = Swift.String()

  /// Required. A directory inside the VM instance's file system where the
  /// storage resource should be mounted (e.g., `/mnt/share`).
  public var localMount: Swift.String = Swift.String()

  /// Initialize a new instance of `StorageConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StorageConfig().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.StorageConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
