// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Describes how a storage resource should be initialized. Each storage resource
/// can either be imported from an existing Google Cloud resource or initialized
/// when the cluster is created.
public struct StorageResourceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Particular type of configuration for this storage resource.
  public var config: OneOf_Config? = nil

  /// Initialize a new instance of `StorageResourceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StorageResourceConfig().with { $0.newFilestore = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case newFilestore = "newFilestore"
    case existingFilestore = "existingFilestore"
    case newBucket = "newBucket"
    case existingBucket = "existingBucket"
    case newLustre = "newLustre"
    case existingLustre = "existingLustre"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var config: OneOf_Config? = nil
    let configCheckAndSet = {
      if config != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'config'"))
      }
      config = $0
    }
    if let newFilestore = try container.decodeIfPresent(
      NewFilestoreConfig?.self, forKey: .newFilestore)
    {
      try configCheckAndSet(.newFilestore(newFilestore))
    }
    if let existingFilestore = try container.decodeIfPresent(
      ExistingFilestoreConfig?.self, forKey: .existingFilestore)
    {
      try configCheckAndSet(.existingFilestore(existingFilestore))
    }
    if let newBucket = try container.decodeIfPresent(NewBucketConfig?.self, forKey: .newBucket) {
      try configCheckAndSet(.newBucket(newBucket))
    }
    if let existingBucket = try container.decodeIfPresent(
      ExistingBucketConfig?.self, forKey: .existingBucket)
    {
      try configCheckAndSet(.existingBucket(existingBucket))
    }
    if let newLustre = try container.decodeIfPresent(NewLustreConfig?.self, forKey: .newLustre) {
      try configCheckAndSet(.newLustre(newLustre))
    }
    if let existingLustre = try container.decodeIfPresent(
      ExistingLustreConfig?.self, forKey: .existingLustre)
    {
      try configCheckAndSet(.existingLustre(existingLustre))
    }
    self.config = config
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.config {
      switch choice {
      case .newFilestore(let value):
        try container.encode(value, forKey: .newFilestore)
      case .existingFilestore(let value):
        try container.encode(value, forKey: .existingFilestore)
      case .newBucket(let value):
        try container.encode(value, forKey: .newBucket)
      case .existingBucket(let value):
        try container.encode(value, forKey: .existingBucket)
      case .newLustre(let value):
        try container.encode(value, forKey: .newLustre)
      case .existingLustre(let value):
        try container.encode(value, forKey: .existingLustre)
      }
    }
  }

  /// Particular type of configuration for this storage resource.
  public enum OneOf_Config: Codable, Equatable, Sendable {
    /// Optional. Immutable. If set, indicates that a new Filestore instance
    /// should be created.
    indirect case newFilestore(NewFilestoreConfig?)
    /// Optional. Immutable. If set, indicates that an existing Filestore
    /// instance should be imported.
    indirect case existingFilestore(ExistingFilestoreConfig?)
    /// Optional. Immutable. If set, indicates that a new Cloud Storage bucket
    /// should be created.
    indirect case newBucket(NewBucketConfig?)
    /// Optional. Immutable. If set, indicates that an existing Cloud Storage
    /// bucket should be imported.
    indirect case existingBucket(ExistingBucketConfig?)
    /// Optional. Immutable. If set, indicates that a new Managed Lustre instance
    /// should be created.
    indirect case newLustre(NewLustreConfig?)
    /// Optional. Immutable. If set, indicates that an existing Managed Lustre
    /// instance should be imported.
    indirect case existingLustre(ExistingLustreConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.hypercomputecluster.v1.StorageResourceConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
